name: test
url: https://github.com/acocac/scivision-test-plugin.git
import: scivision_test_plugin
model: ImageNetModel
args: None
prediction_fn:
    call: predict
    args:
        X: image
    kwargs: None