name: test
url: https://github.com/quantumjot/scivision-test-plugin.git
import: scivision_test_plugin
model: DummyModel
args: None
prediction_fn:
    call: predict
    args:
        X: image
    kwargs:
        - sigma
